In [ ]:
import torch
import numpy as np

In [ ]:
##random tensor


In [ ]:
random_tensor=torch.rand(3,4)
random_tensor


tensor([[0.3109, 0.5013, 0.5767, 0.3120],
        [0.0468, 0.6942, 0.1526, 0.8301],
        [0.2683, 0.0378, 0.7265, 0.1046]])

In [ ]:
random_tensor.ndim

2

create a random tensor with similar shape to the image


In [ ]:
random_tensor_image_size=torch.rand([224,224,3])

random_tensor_image_size.shape,random_tensor_image_size.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
###data types in tensors


In [ ]:
my_tensor=torch.tensor([3,4],dtype=torch.float32)


In [ ]:
my_tensor.dtype

torch.float32

In [ ]:
##getting information in

##tensor not right datatype---to do gte datatype from a tensor, can use tensor.dtype
##tensors not rifht shape---to get shape from a tensor, can use tensor.shape
##tensors not on the right device---to get device from a tensor, can use tensor.device

In [ ]:
some_tensor=torch.rand(3,4
                       )
some_tensor

tensor([[0.3850, 0.3550, 0.1062, 0.6059],
        [0.6729, 0.9762, 0.3888, 0.3655],
        [0.7967, 0.3539, 0.7430, 0.3033]])

In [ ]:
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of the tensor: {some_tensor.shape}')
print(f'device of the tensor: {some_tensor.device}')

Datatype of tensor: torch.float32
Shape of the tensor: torch.Size([3, 4])
device of the tensor: cpu


###Manipulating tensors
Tensor operations include:
* Addition
* Substraction
* Multiplication(element-wise)
* Division
* Matrix Multiplication

In [ ]:
tensor=torch.tensor([1,2,3])

In [ ]:
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor * tensor

tensor([1, 4, 9])

In [ ]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.remainder(tensor,2)

tensor([1, 0, 1])

###Matrix multiplication


In [ ]:
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
a=torch.tensor([[1,2,3],[4,5,6]])
b=torch.tensor([[7,8,9],[1,2,3],[5,6,7]])
torch.matmul(a,b)

tensor([[24, 30, 36],
        [63, 78, 93]])

#Reshaping, stacking, squeezing, unsqueezing tesnsors

* Reshaping- reshapes an input tensor to a defined shape
* view- return a view of an inout tensor of certain shape but keep the same memory as the original tensors
* stacking- combines multiple tensors on top of each other(vstack) or side by side(hstack)
* squeez- removes all '1' dimensions from a tensor
* unsqueez - add a '1' dimensions to a targer tensor
* permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
#create a tensor
import torch
x=torch.arange(1.,9.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8.]), torch.Size([8]))

In [ ]:
x_reshaped =x.reshape(1,8) #added a single dimension
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]), torch.Size([1, 8]))

In [ ]:
x_reshaped=x.reshape(8,1)
x_reshaped,x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.]]),
 torch.Size([8, 1]))

In [ ]:
x_reshaped=x.reshape(2,4)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4.],
         [5., 6., 7., 8.]]),
 torch.Size([2, 4]))

In [ ]:
#change the view
z=x.view(1,8)

z,z.shape,x

(tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]),
 torch.Size([1, 8]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8.]))

In [ ]:
 #stck tensors on top of each other
x_stacked=torch.stack([x,x,x,x],dim=0)
x_stacked,x_stacked.shape,x_stacked.ndim

(tensor([[1., 2., 3., 4., 5., 6., 7., 8.],
         [1., 2., 3., 4., 5., 6., 7., 8.],
         [1., 2., 3., 4., 5., 6., 7., 8.],
         [1., 2., 3., 4., 5., 6., 7., 8.]]),
 torch.Size([4, 8]),
 2)

#Pytorch tensors and numpy

pytorch has functionality to interact with numpy

* Data in NumPy, want in PyTorch tensors -> torch.from_numpy(ndarray)

* PyTorch tensors -> Numpy -> torch.Tensor.numpy()

In [ ]:
 #Numpy array to tensor
 import torch
 import numpy as np

 array=np.arange(1.,8.)
 tensor=torch.from_numpy(array).type(torch.float32)
 array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
tensor.dtype

torch.float32

In [ ]:
#tensor to numpy
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

#Reproducibility

In short how a neural networks learns:

'start with random numbers -> tesnor operation -> update random nubers to try and make them better representations of the data -> again -> again ->......o


To reduce the randomness in neural network and PyTorch comes the concept of **random seed**

Essentially what the random seed does is "flavour" the randomness


In [ ]:
import torch

#create two tensors

random_tensor_a=torch.rand(3,4)
random_tensor_b=torch.rand(3,4)

print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a==random_tensor_b)

tensor([[0.1809, 0.8033, 0.0790, 0.3073],
        [0.2264, 0.3839, 0.8639, 0.2235],
        [0.1460, 0.1123, 0.0686, 0.5685]])
tensor([[0.3787, 0.9379, 0.0764, 0.9863],
        [0.3740, 0.0885, 0.1174, 0.6120],
        [0.6452, 0.9820, 0.3247, 0.0979]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
 #lets make some random but reproducible tensors
import torch
#set the random seed
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
random_tensor_c=torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_d=torch.rand(3,4)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c==random_tensor_d)






tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# extra resources for reproducibility
* https://docs.pytorch.org/docs/2.13/notes/randomness.html

#Running tensors and pytorch objects on the GPUs(and making faster computation)


* GPU means faster computation on numbers

* CUDA + NVIDIA hardware + PYTorch


In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
device = "cuda" if torch.cuda.is_available() else device=="cpu"
device

'cuda'

In [ ]:
torch.cuda.device_count()

1

In [ ]:
tensor=torch.tensor([1,2,3])
tensor,tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
#Move tensor to GPU
tensor_on_gpu=tensor.to("cuda")
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
  ,.